---
output:
  pdf_document: default
  html_document: default
---
%-------------------------
  % Resume in Latex
% Author : Drew Hultquist
% License : MIT
%------------------------

  \documentclass[letterpaper,11pt]{article}

\usepackage{latexsym}
\usepackage[empty]{fullpage}
\usepackage{titlesec}
\usepackage{marvosym}
\usepackage[usenames,dvipsnames]{color}
\usepackage{verbatim}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\usepackage{fancyhdr}
\usepackage[english]{babel}
\usepackage{tabularx}
\input{glyphtounicode}


%----------FONT OPTIONS----------
  % sans-serif
% \usepackage[sfdefault]{FiraSans}
% \usepackage[sfdefault]{roboto}
% \usepackage[sfdefault]{noto-sans}
% \usepackage[default]{sourcesanspro}

% serif
% \usepackage{CormorantGaramond}
% \usepackage{charter}


\pagestyle{fancy}
\fancyhf{} % clear all header and footer fields
\fancyfoot{}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}

% Adjust margins
\addtolength{\oddsidemargin}{-0.5in}
\addtolength{\evensidemargin}{-0.5in}
\addtolength{\textwidth}{1in}
\addtolength{\topmargin}{-.5in}
\addtolength{\textheight}{1.0in}

\urlstyle{same}

\raggedbottom
\raggedright
\setlength{\tabcolsep}{0in}

% Sections formatting
\titleformat{\section}{
  \vspace{-4pt}\scshape\raggedright\large
}{}{0em}{}[\color{black}\titlerule \vspace{-5pt}]

% Ensure that generate pdf is machine readable/ATS parsable
\pdfgentounicode=1

%-------------------------
  % Custom commands
\newcommand{\resumeItem}[1]{
  \item\small{
    {#1 \vspace{-2pt}}
    }
  }

  \newcommand{\resumeSubheading}[4]{
    \vspace{-2pt}\item
    \begin{tabular*}{0.97\textwidth}[t]{l@{\extracolsep{\fill}}r}
    \textbf{#1} & #2 \\
      \textit{\small#3} & \textit{\small #4} \\
        \end{tabular*}\vspace{-7pt}
      }

      \newcommand{\resumeSubSubheading}[2]{
        \item
        \begin{tabular*}{0.97\textwidth}{l@{\extracolsep{\fill}}r}
        \textit{\small#1} & \textit{\small #2} \\
          \end{tabular*}\vspace{-7pt}
        }

        \newcommand{\resumeProjectHeading}[2]{
          \item
          \begin{tabular*}{0.97\textwidth}{l@{\extracolsep{\fill}}r}
          \small#1 & #2 \\
          \end{tabular*}\vspace{-7pt}
        }

        \newcommand{\resumeSubItem}[1]{\resumeItem{#1}\vspace{-4pt}}

          \renewcommand\labelitemii{$\vcenter{\hbox{\tiny$\bullet$}}$}

          \newcommand{\resumeSubHeadingListStart}{\begin{itemize}[leftmargin=0.15in, label={}]}
          \newcommand{\resumeSubHeadingListEnd}{\end{itemize}}
          \newcommand{\resumeItemListStart}{\begin{itemize}}
          \newcommand{\resumeItemListEnd}{\end{itemize}\vspace{-5pt}}

          %-------------------------------------------
            %%%%%%  RESUME STARTS HERE  %%%%%%%%%%%%%%%%%%%%%%%%%%%%


            \begin{document}

          %----------HEADING----------


            \begin{center}
          \textbf{\Huge \scshape Drew Hultquist} \\ \vspace{1pt}
          \small 308-850-6046 $|$ \href{mailto:ahultquist2@huskers.unl.edu}{\underline{ahultquist2@huskers.unl.edu}} $|$
          


          %-----------EDUCATION-----------
            \section{Education}
          \resumeSubHeadingListStart
          \resumeSubheading
          {Chadron State College}{Chadron, NE}
          {Bachelor of Science in Math and Business}
          {Graduated May 2021}
            


          \resumeItemListEnd


          \resumeSubheading
          {University of Nebraska-Lincoln}{Lincoln, NE}
          {Statistics Masters Degree}{Expected May 2023}

          
          \resumeItemListEnd

          \resumeSubHeadingListEnd



          %-----------EXPERIENCE-----------
            \section{ Professional Experience}
          \resumeSubHeadingListStart

          \resumeSubheading
          {Graduate Teaching Assistantship}{August 2021 – Current}
          {University of Nebraska Lincoln}{Lincoln, NE}
          \resumeItemListStart
          \resumeItem{	Help teach a introductory statistics class to undergraduate students }
          \resumeItem{Help give presentations to teach new material }
          \resumeItemListEnd

           




          \end{document}
